added lag functions and tests
HewlettPackard/pyhpecfm pull request #10
Opened 2019-07-08 16:37 UTC by xod442

created a get lags function that takes eight parameters. Add the get lags test as well.

2019-07-08 16:51 UTC, bri365 approved these changes

2019-07-10 23:12 UTC, bri365 submitted a review, later dismissed

2019-07-10 23:12 UTC, bri365 commented on pyhpecfm/auth.py
> +        url = 'http://{}/api/{}'.format(self._host, path)
um, this should not work in production - only https is supported

2019-07-10 23:13 UTC, bri365 requested changes
https not http

2019-07-16 22:24 UTC, bri365 approved these changes

2019-07-17 20:27 UTC, xod442 commented
Merging

2019-07-17 20:28 UTC, merged